//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace room_management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class stanze
    {
        public int id { get; set; }
        public string nome { get; set; }
        public Nullable<int> prezzo { get; set; }
        public string descrizione { get; set; }
    }
}
